### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pravinlondhe** [brobwind/BroDm#1]
getting error like below after application execution
07-27 15:35:33.820  5157  5157 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport.so" not found
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at java.lang.Runtime.loadLibrary(Runtime.java:372)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at java.lang.System.loadLibrary(System.java:1076)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at com.brobwind.brodm.Kit.<clinit>(Kit.java:30)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at com.brobwind.brodm.DeviceActivity.onCreate(DeviceActivity.java:115)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:6251)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5461)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-27 15:35:33.820  5157  5157 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-27 15:35:33.822   802  3349 W ActivityManager:   Force finishing activity com.brobwind.brodm/.DeviceActivity
07-27 15:35:33.824   802  3349 W ActivityManager:   Force finishing activity com.brobwind.brodm/.DiscoveryActivity

**Comment by brobwind** [comment]
You may run it under Android 6.0 or above system, which may not contain stlport library. You may try to do a little modification and compile it under android 6.0 project. 
I will check it later.
Thanks!

**Comment by pravinlondhe** [comment]
thanks for response.
I am succeeded by adding stlport library in apk.
